### ISSUE TITLE
CheckPoint1 input form

### ISSUE THREAD

**Issue by juannicolas** [juannicolas/ScavengerRun#1]
Don't know how to make a view to input data to db using a form.

**Comment by promanor** [comment]
You are so close!!

def cp1(request):
    title = "Check Point 1"
    head = "AG Servicio"

    if request.method == "post":
        form = AddTimeForm(request.POST)
        if form.is_valid():
            form.save()
        #print request.post
    else:
        form = AddTimeForm()
    context = {
        "title": title,
        "head": head,
        "form": form
    }
    return render(request, "cp1.html", context)
